### ISSUE TITLE
Unknown type name 'UIBackgroundTaskIdentifier'

### ISSUE THREAD

**Issue by antonigiske** [TransitApp/SVHTTPRequest#49]
Don't know if this lib is supporting iOS8, but I get this message after installing it and trying to run a simple GET request. 

     SVHTTPRequest/SVHTTPRequest.m:46:34: Unknown type name 'UIBackgroundTaskIdentifier'

**Comment by cocoajin** [comment]
```
#import <UIKit/UIApplication.h>
```
